import { KernelCpuInfo } from "./DrvFunction/bios/Cpu/getCpuInfo.js";
import { KernelCpuEndian } from "./DrvFunction/bios/Cpu/getCpuendian.js.js";
import { KernelCpuArch } from "./DrvFunction/bios/Cpu/getCpuArch.js.js";
import { KernelRamAmount } from "./DrvFunction/bios/memory/GetAllram.js";
import { KernelRamFreeMemory } from "./DrvFunction/bios/memory/getfreeMemory.js.js";
import { KernelGetBiosEnvioment } from "./DrvFunction/bios/Cpu/getBiosEnvioment.js";
import { KernelTFSWriteFile } from "./DrvFunction/Filesystem/writefile.js"
import { KernelTFSAppendFile } from "./DrvFunction/Filesystem/appendFile.js.js.js.js"
import { KernelTFSCreateFile } from "./DrvFunction/Filesystem/createfile.js.js.js.js"
import { KernelTFSDeleteFile } from "./DrvFunction/Filesystem/DeleteFile.js.js.js.js"
import { KernelTFSRenameFile } from "./DrvFunction/Filesystem/rname.js"
import { KernelTFSDeleteFolder } from './DrvFunction/Filesystem/DeleteFolder.js.js.js.js';
