import { KernelCpuInfo } from "./drv/function/bios/Cpu/getCpuInfo.js.js";
import { KernelCpuEndian } from "./drv/function/bios/Cpu/getCpuendian.js.js.js";
import { KernelCpuArch } from "./drv/function/bios/Cpu/getCpuArch.js.js.js";
import { KernelRamAmount } from "./drv/function/bios/memory/GetAllram.js";
import { KernelRamFreeMemory } from "./drv/function/bios/memory/getfreeMemory.js.js.js";
import { KernelGetBiosEnvioment } from "./drv/function/bios/Cpu/getBiosEnvioment.js.js";
import { KernelTFSWriteFile } from "./drv/function/Filesystem/writefile.js"
import { KernelTFSAppendFile } from "./drv/function/Filesystem/appendFile.js.js.js.js.js"
import { KernelTFSCreateFile } from "./drv/function/Filesystem/createfile.js.js.js.js.js"
import { KernelTFSDeleteFile } from "./drv/function/Filesystem/DeleteFile.js.js.js.js.js"
import { KernelTFSRenameFile } from "./drv/function/Filesystem/rname.js"
import { KernelTFSDeleteFolder } from './drv/function/Filesystem/DeleteFolder.js.js.js.js.js';
